name: CI/CD for .NET App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'  # або ваша версія .NET

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # Запуск конкретних тестів з файлу або класу
    - name: Run specific tests
      run: dotnet test --filter "CalcApp.Test.Calculator.cs" --no-restore --verbosity normal

    # Виводимо повідомлення про помилки, якщо вони є
    - name: Check for test failures
      if: failure()
      run: echo "❌ Some tests failed. Check the logs for more details."
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Deploy application
      run: echo "Deploying application..."
