name: CI/CD for CalcApp

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонуємо репозиторій
      - name: Checkout repository
        uses: actions/checkout@v3

      # Встановлюємо .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # або ваша версія .NET

      # Відновлюємо залежності
      - name: Restore dependencies
        run: dotnet restore

      # Білдимо проєкт
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Запускаємо конкретні тести
      - name: Run specific tests with detailed output
        run: dotnet test --no-restore --logger "console;verbosity=detailed"

      # Виводимо повідомлення про помилки, якщо такі є
      - name: Check for test failures
        if: failure()
        run: echo "❌ Some tests failed. Check the logs for more details."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Deploy application
        run: echo "Deploying application..."
        # Сюди можна додати реальний деплой скрипт
